apiVersion: v1
kind: Service
metadata:
  name: single-app-single-collector
  labels:
    app: single-app-single-collector
  namespace: aks-demo
spec:
  type: ClusterIP
  selector:
    app: single-app-single-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
     
      

